import { w, type Project } from './types';

export const projects: Project[] = [
  {
    id: 'balanzify',
    name: 'Balanzify',
    tagline: 'Multi-tenant SaaS accounting platform',
    href: 'https://balanzify.com',
    hrefLabel: 'balanzify.com',
    status: 'production',
    tier: 1,
    summary:
      'Invoicing, payroll, HRIS, inventory and journals for real businesses — I architected the Django backend, owned the PostgreSQL data model end to end, and shipped the LLM features running against live user data.',
    bullets: [
      '40+ Django apps, 600+ models and 350+ DRF endpoints across end-user, workspace, admin and public API surfaces.',
      'Owned the PostgreSQL data model end to end — schema design, indexing, query optimisation and safe migrations against a live database.',
      'JWT auth, Google OAuth2 SSO, OTP/MFA, per-endpoint permissions and RBAC, row-level tenant isolation, audit logging, full model history and OpenAPI/Swagger docs.',
      'Load-tested to ~1,000 req/min at <300 ms p95 and 500+ concurrent WebSocket connections on an async ASGI stack (Daphne) with PostgreSQL on RDS.',
      'Celery + Redis workers keep API latency low — receipt OCR (GPT-4 Vision + Tesseract), LLM transaction categorisation (OpenAI/Groq), financial reports and outbound webhooks.',
      'Real-time chat and notifications over Django Channels + Redis pub/sub.',
      'Integrated Plaid, Stripe, Moov and TaxBandits (IRS 940/941 e-filing); fully automated AWS pipeline (CodeBuild → CodeDeploy → EC2) with Docker-based deployments.',
    ],
    stack: [
      'Django',
      'DRF',
      'PostgreSQL',
      'Redis',
      'Celery',
      'Channels',
      'Docker',
      'AWS EC2 · RDS · S3',
      'CodeDeploy',
    ],
    weight: w(1.0, 0.75, 0.8, 1.0),
  },
  {
    id: 'gostyle',
    name: 'GoStyle',
    tagline: 'Multi-tenant SaaS platform for POS & bookings',
    href: 'https://business.gostyle.uk',
    hrefLabel: 'business.gostyle.uk',
    status: 'production',
    tier: 1,
    summary:
      'A platform, not an app: 18 independently versioned libraries composed into one host API, so a new product writes only domain code. Correctness under retries is enforced by the architecture, not by convention.',
    bullets: [
      'Monorepo of 18 independently versioned NestJS libraries — auth, RBAC, audit, outbox, idempotency, loyalty, sales, bookings — composed into one host API.',
      '114-table PostgreSQL schema (116 migrations) for POS/billing, FIFO inventory costing, bookings, RBAC and loyalty; money stored as integer fils to avoid floating-point drift, partial unique indexes for tenant-scoped constraints.',
      'Hexagonal architecture + CQRS with dependency direction enforced at CI time via eslint-plugin-boundaries — an architectural rule that fails the build, not a wiki page.',
      'Transactional outbox for at-least-once event delivery and encrypted per-tenant idempotency, so a retried POST cannot double-charge or double-book.',
      'Tenant isolation and RBAC with last-admin protection; ~392 Vitest test files run against a real PostgreSQL container in CI.',
      'Zero-downtime deploys on Docker Swarm via GitHub Actions, with Grafana + Loki observability across service boundaries.',
      'A Go microservice with its own API boundary interoperates with the TypeScript platform across a defined contract, not a shared codebase.',
    ],
    stack: [
      'NestJS 11',
      'TypeScript',
      'Go',
      'PostgreSQL',
      'gRPC',
      'Docker Swarm',
      'GitHub Actions',
      'Vitest',
      'Grafana · Loki',
    ],
    weight: w(1.0, 1.0, 0.25, 0.7),
  },
  {
    id: 'agentvcr',
    name: 'agentvcr',
    tagline: 'Open-source “VCR” for AI agents',
    href: 'https://pypi.org/project/agentvcr/',
    hrefLabel: 'PyPI / npm · Apache-2.0',
    status: 'open-source',
    tier: 1,
    summary:
      'Agent runs are nondeterministic and expensive to re-run, which makes them untestable. agentvcr records every LLM and tool call behind a one-line base_url change and replays them offline, deterministically, at zero token cost.',
    bullets: [
      'Drop-in LLM proxy that records every LLM and tool call from any agent run — OpenAI/Anthropic-compatible, including Groq, Gemini, OpenRouter, Ollama and vLLM — with a single base_url change and no SDK integration.',
      'Positional replay with request fingerprinting (a normalised hash of model, messages and tools) under warn / strict / live-on-miss policies.',
      'Validated against LangGraph and the OpenAI Agents SDK: nondeterministic fan-out is flagged as diverged rather than silently replaying the wrong result.',
      'React + Vite UI with side-by-side run diffs and a mid-run editor for prompts, tool results and responses, backed by a semantic differ (LCS over step fingerprints) that filters noise and points at the first divergence.',
      'Run forking — fix a failing step and rerun from there — via tape-replay-then-live-fallthrough.',
      'Exit-code-driven `agentvcr diff` CLI turns agent-run verification into a merge/deploy gate; header redaction keeps secrets off disk.',
    ],
    stack: ['Python', 'FastAPI', 'httpx', 'SQLite', 'React', 'Vite', 'TypeScript'],
    weight: w(0.7, 0.7, 1.0, 0.9),
  },
  {
    id: 'rhombus',
    name: 'Rhombus',
    tagline: 'Distributed event orchestration platform',
    status: 'open-source',
    tier: 1,
    summary:
      'Keeps PostgreSQL, Kafka, Redis and Elasticsearch in agreement without a distributed transaction — the atomic-write-plus-publish problem, solved with the transactional outbox pattern.',
    bullets: [
      'Reliable data synchronisation across PostgreSQL, Kafka, Redis and Elasticsearch without distributed transactions.',
      'Transactional Outbox for atomic writes plus event publication, eliminating drift between the database and downstream systems.',
      'Delivery path built around at-least-once semantics, concurrent consumers, retry and partial-failure handling, and eventual consistency.',
    ],
    stack: ['Go', 'Kafka', 'Redis', 'Elasticsearch', 'PostgreSQL'],
    weight: w(0.95, 0.85, 0.15, 0.35),
  },
  {
    id: 'playzone',
    name: 'Playzone',
    tagline: 'Real-time multiplayer game platform',
    period: '2024 – present',
    status: 'production',
    tier: 1,
    summary:
      'Share a link and play instantly, no signup. The interesting part is not the games — it is that a dropped connection never loses the match.',
    bullets: [
      'Next.js + Tailwind front end through NestJS microservices, with live state over Socket.IO at sub-second sync.',
      'Reconnect and turn-state handling so a dropped connection resumes the match instead of forfeiting it.',
      'Game logic and matchmaking split into separate services with PostgreSQL-backed state.',
    ],
    stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'NestJS', 'Socket.IO', 'PostgreSQL', 'Docker'],
    weight: w(0.6, 0.4, 0.1, 0.95),
  },
  {
    id: 'orbit',
    name: 'Orbit',
    tagline: 'Lightweight container orchestration platform',
    status: 'open-source',
    tier: 2,
    summary:
      'A small container orchestrator in Go — scheduling and lifecycle without the Kubernetes surface area.',
    bullets: [],
    stack: ['Go'],
    weight: w(0.5, 1.0, 0.1, 0.2),
  },
  {
    id: 'twinflow',
    name: 'Twinflow',
    tagline: 'Traffic-replay shadow-testing harness',
    status: 'open-source',
    tier: 2,
    summary:
      'Replays real production traffic against a candidate build to catch breaking API changes and regressions before they deploy.',
    bullets: [],
    stack: ['Go'],
    weight: w(0.7, 0.95, 0.3, 0.25),
  },
  {
    id: 'university-erp',
    name: 'University ERP',
    tagline: 'Academic system for students, results, payroll and HR',
    status: 'archived',
    tier: 2,
    summary:
      'A full academic ERP — students, results, payroll and HR records — on Spring Boot and PostgreSQL with a React front end, deployed via CI/CD.',
    bullets: [],
    stack: ['Spring Boot', 'Java', 'PostgreSQL', 'React', 'CI/CD'],
    weight: w(0.7, 0.4, 0.05, 0.8),
  },
];

export const projectById = (id: string) => projects.find((p) => p.id === id);
