import { w, type SkillGroup } from './types';

/**
 * The lens dims low-weight groups rather than hiding them — the breadth is the
 * point, so nothing is ever removed from view.
 */
export const stack: SkillGroup[] = [
  {
    id: 'languages',
    label: 'Languages',
    items: ['Python', 'TypeScript', 'Go', 'Java', 'JavaScript', 'C++', 'SQL', 'Bash'],
    weight: w(0.9, 0.8, 0.7, 0.9),
  },
  {
    id: 'backend',
    label: 'Backend',
    items: [
      'Django',
      'Django REST Framework',
      'NestJS',
      'FastAPI',
      'Spring Boot',
      'REST API design',
      'gRPC',
      'WebSockets',
      'OpenAPI / Swagger',
    ],
    weight: w(1.0, 0.5, 0.5, 0.9),
  },
  {
    id: 'frontend',
    label: 'Frontend',
    items: [
      'React',
      'Next.js',
      'TypeScript',
      'Vite',
      'Tailwind CSS',
      'Real-time UIs (Socket.IO / WebSockets)',
      'Component architecture',
      'State management',
    ],
    weight: w(0.3, 0.2, 0.4, 1.0),
  },
  {
    id: 'data',
    label: 'Data',
    items: [
      'PostgreSQL',
      'MySQL',
      'MongoDB',
      'Redis',
      'SQLite',
      'Elasticsearch',
      'pgvector',
      'Schema design',
      'Indexing & query optimisation',
      'Safe migrations',
    ],
    weight: w(1.0, 0.6, 0.5, 0.75),
  },
  {
    id: 'messaging',
    label: 'Messaging & events',
    items: [
      'Kafka',
      'RabbitMQ',
      'Celery',
      'Redis pub/sub',
      'Django Channels',
      'Socket.IO',
      'Transactional outbox',
      'Idempotency',
    ],
    weight: w(1.0, 0.7, 0.3, 0.7),
  },
  {
    id: 'architecture',
    label: 'Architecture',
    items: [
      'Microservices',
      'Hexagonal (Ports & Adapters)',
      'CQRS',
      'Event-driven',
      'Multi-tenancy',
      'DDD',
      'Design patterns',
    ],
    weight: w(1.0, 0.85, 0.35, 0.6),
  },
  {
    id: 'cloud',
    label: 'Cloud & DevOps',
    items: [
      'AWS (EC2, RDS, S3, CodeBuild, CodeDeploy)',
      'Docker',
      'Docker Swarm',
      'Kubernetes',
      'GitHub Actions',
      'CI/CD',
      'Zero-downtime deploys',
    ],
    weight: w(0.6, 1.0, 0.4, 0.55),
  },
  {
    id: 'observability',
    label: 'Observability & testing',
    items: [
      'Prometheus',
      'Grafana',
      'Loki',
      'Structured logging',
      'SLI / SLO',
      'Load testing',
      'pytest',
      'Vitest',
      'Integration tests against real DBs',
      'ESLint boundary enforcement',
    ],
    weight: w(0.7, 1.0, 0.5, 0.5),
  },
  {
    id: 'ai',
    label: 'AI & LLM',
    items: [
      'OpenAI · Anthropic · Groq APIs',
      'Tool / function calling',
      'Structured output',
      'Streaming',
      'RAG & embeddings',
      'LangGraph',
      'OpenAI Agents SDK',
      'Vision OCR',
      'Evals',
      'Token-cost optimisation',
      'MCP servers',
      'Claude Code',
    ],
    weight: w(0.3, 0.35, 1.0, 0.4),
  },
  {
    id: 'integrations',
    label: 'Auth & integrations',
    items: [
      'JWT',
      'OAuth2 / Google SSO',
      'OTP-MFA',
      'RBAC',
      'Stripe',
      'Plaid',
      'Moov',
      'TaxBandits',
      'Webhooks',
    ],
    weight: w(0.9, 0.4, 0.2, 0.8),
  },
];
